SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME FROM ANIMAL_INS A
LEFT OUTER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE = "Intact Male" and B.SEX_UPON_OUTCOME = "Neutered Male" and A.ANIMAL_ID = B.ANIMAL_ID OR A.SEX_UPON_INTAKE = "Intact Female" and B.SEX_UPON_OUTCOME = "Spayed Female" and A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY A.ANIMAL_ID;